### PR TITLE
bump up version for RubyGem

### PR DESCRIPTION
**Pull request by eugenejen**

### CODE REVIEW

**Comment by eugenejen** [comment]
I signed it!

**Comment by planas** [comment]
+1

**Comment by archana-juvo** [comment]
+1 
When is the new version of gem being released? 
https://rubygems.org/gems/google-id-token/versions/1.3.1 has pretty old code.

**Comment by dhh** [comment]
Thirded!

**Comment by morgoth** [comment]
@gguuss @mrstif Can we have a new version released, please? When starting to integrate one have to go to source code to realize that there is a mismatch in released gem code and documentation in the readme.

**Comment by morgoth** [comment]
@gguuss Thanks for merging, but the new version is still not released, vide https://rubygems.org/gems/google-id-token - can you push the new gem, please?

**Pull request merged**
