### PR TITLE
Thread-safety & better certificate caching

### PR DESCRIPTION
**Pull request by mrstif**
This PR tries to solve the issues summarized in issues https://github.com/google/google-id-token/issues/6 and https://github.com/google/google-id-token/issues/7

To make the `Validator` thread-safe, I removed all the instance variables from it, except for certificates cache-related stuff. For diagnosing problems I am raising specific errors instead.

To improve the caching mechanism I introduced an `expiry` option which defines the time after which the certificates cache should be renewed. This prevents continuously fetching them in case of constant decoding errors.

### CODE REVIEW

**Comment by igorescobar** [comment]
+1

**Comment by mrstif** [comment]
I signed it!

**Comment by gguuss** [comment]
I made the other commit to address concern, I approve.

**Comment by gguuss** [comment]
I confirm

**Comment by gguuss** [comment]
@remi FYI

**Pull request merged**
